# Generated by Django 4.1.3 on 2022-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderBooking",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("unique_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "order_booking",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("qrcode", models.CharField(blank=True, max_length=254, null=True)),
                ("code", models.CharField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("po", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "tolerance",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "loss_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("customer_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_pattern_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "supplier_delivery_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("tax_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "payment_method_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("currency_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "debit_detail_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("is_complete", models.IntegerField()),
                ("vnd_exchange_rate", models.FloatField(blank=True, null=True)),
                ("vnd_exchange", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderQuota",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "quota",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "loss_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("total_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_quota",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("order_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_booking_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "specification",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "db_table": "order_quota",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("order_type", models.CharField(blank=True, max_length=45, null=True)),
                ("unique_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tracking_order_detail_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "tracking_order_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
    ]
