# Generated by Django 4.1.3 on 2022-11-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialReports",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("is_calculated", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
            ],
            options={
                "db_table": "material_reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                ("qrcode", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "specification",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "reserve_quantity",
                    models.DecimalField(decimal_places=10, max_digits=24),
                ),
                ("leak_time", models.FloatField()),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product_type_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "product_color_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "product_specification_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("supplier_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("short_code", models.CharField(blank=True, max_length=10, null=True)),
                ("is_outsourcing", models.IntegerField()),
                ("gallery_id", models.BigIntegerField(blank=True, null=True)),
                ("default_img", models.BigIntegerField(blank=True, null=True)),
                ("in_trash", models.IntegerField()),
            ],
            options={
                "db_table": "product_detail",
                "managed": False,
            },
        ),
    ]
