# Generated by Django 4.1.3 on 2022-11-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_materialreports_productdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutsourcingProductMaterials",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "outsourcing_product_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                (
                    "report_product_need_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "report_primary_product_need_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "outsourcing_product_materials",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="materialreports",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="orderbooking",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="orderdetail",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="orderquota",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="productdetail",
            options={"managed": True},
        ),
    ]
