# Generated by Django 4.1.3 on 2022-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_outsourcingproductmaterials_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialReportHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
            ],
            options={
                "db_table": "material_report_history",
                "managed": False,
            },
        ),
    ]
