# Generated by Django 4.1.3 on 2022-11-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_materialreporthistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialreports",
            options={"managed": False},
        ),
    ]
